### PR TITLE
changed h1

### PR DESCRIPTION
**Pull request by carlosmendes**
I changed the home file on views. Please review it @filipe-p

### CODE REVIEW

**Comment by Filipe-p** [comment]
Hummm I need to think about this

**Comment by Filipe-p** [comment]
This is ugly. You can do better

**Comment by carlosmendes** [comment]
just add one exclamation mark!!!!!

**Comment by Filipe-p** [comment]
Focus guys!

**Review by Filipe-p — CHANGES_REQUESTED** [review]
Remove the !!👍

**Review by Filipe-p — APPROVED** [review]
I like it!✌👍

**Pull request merged**
